// Per-lesson verse index: maps each Qur'anic verse discussed in a lesson to
// the paragraph (in BilingualText's `commentaryParagraphs` / `ar-para-N` id
// scheme) where it is FIRST quoted, so a verse-jump bar can scroll straight
// to it -- Jalalayn-style, per-ayah navigation, layered on top of Niasse's
// lesson-based oral commentary rather than restructuring it.
//
// Built by matching the Arabic clauses the compiler brackets in ( ), « » or
// { } against the Warsh ʿan Nāfiʿ text the edition follows
// (scripts/match-verses.js -> scripts/build-verse-citations.js ->
// scripts/add-editorial-verse-index.js), then pruned of entries pointing past
// the end of their lesson (scripts/prune-stale-para-indices.js).
//
// paraIndex is 0-based, matching the index BilingualText.tsx assigns after
// filtering poem/basmala lines out of arabicBody||arabicText.split('\n').
//
// THERE WAS A HAND-CURATED TABLE HERE, FOR LESSONS 1-3, AND IT IS GONE.
// It was written when the matcher was worse, and the merge below it was
// written to make the curation win: a curated lesson kept its own rows and
// took nothing from the automated index but unbracketed quotations. Both
// halves of that arrangement had since failed.
//
// The rows went stale. `arabicBody` was rebuilt in August and the paragraph
// array shifted by about four; lesson1FatihaVerseMap.ts was re-anchored
// against the rebuild on 2026-08-19 and this table was not, so it kept
// sending Q 1:2-1:4 to paragraph 58 when the verses are at 53-55, and Q 2:25
// to paragraph 37 of a lesson with 36 paragraphs. Checked against the text
// in September 2026 -- does any paragraph carry three consecutive words of
// the āya -- the automated index is right for every verse tested in all
// three lessons and the curated table is wrong for all but three. The effect
// was that the only three lessons AK has read against the printing had the
// least accurate verse pages on the site.
//
// And the merge's one addition stopped arriving. It filtered the automated
// rows on `inferred`, a field add-editorial-verse-index.js stopped writing;
// the flag is now `editorial`, so the unbracketed identifications the merge
// existed to preserve -- Q 42:11 in Lesson 1 among them -- were being
// dropped for the three lessons the merge covered.
//
// A curated table is worth having again only with something enforcing the
// coupling to the text. Until then the automated index is the honest answer:
// it is regenerated by the pipeline whenever the bodies change, so it cannot
// silently drift out from under them.

import autoIndexRaw from '@/data/verseIndexAuto.json';

export interface VerseIndexEntry {
  /** e.g. "2:26" */
  verse: string;
  /** 0-based index into commentaryParagraphs / id="ar-para-{paraIndex}" */
  paraIndex: number;
  /** Set when the match is uncertain (partial quote, compound citation, etc.) */
  uncertain?: boolean;
  /**
   * The printing does not bracket this quotation; the project identified it.
   *
   * Everything else in this index comes from a span the compiler enclosed in
   * ( ), « » or { }, so the edition itself declares it a citation. These
   * entries rest on a different warrant: a run of five consecutive words
   * occurring word-aligned in exactly one āya of the 6,236 and nowhere else
   * (scripts/index-unbracketed-ayat.js). Strong, and still a reading rather
   * than a report, so the badge has to say which it is.
   */
  editorial?: boolean;
}

const AUTO_VERSE_INDEX = autoIndexRaw as unknown as Record<string, VerseIndexEntry[]>;

// Al-Fatiha, lesson 1, and nothing else. These four are ADDED where the
// matcher has no row; they never replace one, which is the whole difference
// from the table that used to sit here.
//
// The matcher cannot reach them, and the reason is structural rather than a
// bug to fix. Its floor is three significant words, which exists because
// Q 2:1 is "alif lam mim" and without a floor the muqatta'at matched half the
// corpus. Al-Fatiha's verses are shorter than that floor, and the Shaykh
// brackets them lemma by lemma -- paragraph 53 reads "(al-hamdu li-llah) ...
// (rabbi l-'alamin) tawhid, (al-rahman al-rahim) wa'd, (maliki yawmi l-din)
// wa'id", four brackets of two words each. So the sura every visitor arrives
// on is the one the matcher is structurally blind to.
//
// Each index below is the paragraph where the verse is FIRST bracketed, read
// off the text: 1:1 at the head of the basmala discussion (paragraph 27,
// which opens by quoting it and asking whether it is an aya of the Fatiha),
// 1:2 and 1:3 in the genre-classification pass at 53, 1:5 beside 1:6 at 54.
// The matcher's own rows for 1:4 (53), 1:6 (54) and 1:7 (55) agree with that
// reading, which is the check on it.
const FATIHA_LESSON_1: VerseIndexEntry[] = [
  { verse: '1:1', paraIndex: 27 },
  { verse: '1:2', paraIndex: 53 },
  { verse: '1:3', paraIndex: 53 },
  { verse: '1:5', paraIndex: 54 },
];

export const VERSE_INDEX: Record<number, VerseIndexEntry[]> = {
  ...(AUTO_VERSE_INDEX as unknown as Record<number, VerseIndexEntry[]>),
};
{
  const held = new Set((VERSE_INDEX[1] || []).map(e => e.verse));
  const add = FATIHA_LESSON_1.filter(e => !held.has(e.verse));
  if (add.length) {
    VERSE_INDEX[1] = [...(VERSE_INDEX[1] || []), ...add]
      .sort((a, b) => a.paraIndex - b.paraIndex);
  }
}
