import Link from 'next/link';

export default function IntroductionPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 pb-20 pt-6" dir="ltr">
      <div className="text-center pb-8 mb-8 border-b border-gold/20">
        <div className="font-english text-gold text-2xl font-semibold italic">
          Translator&apos;s Introduction
        </div>
        <div className="font-english text-white/50 text-sm mt-2">
          In the Gardens of Exegesis: The Tafsīr of Shaykh Ibrāhīm Niasse
        </div>
        <p className="font-english text-white font-semibold text-center mt-4">Amadu Kunateh</p>
        <p className="font-english text-white/45 text-sm text-center">PhD Candidate, Philosophy of Religion and African Studies</p>
        <p className="font-english text-white/45 text-sm text-center">Harvard University</p>
      </div>
      <h2 className="font-english text-gold text-xl font-semibold mt-10 mb-4 pb-3 border-b border-gold/20">Shaykh Ibrāhīm Niasse and the West African Scholarly Tradition</h2>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">Shaykh Ibrāhīm Niasse (d. 1975), the twentieth-century Senegalese scholar and leader of the Fayḍa branch of the Tijāniyya ṭarīqa, is regarded by his followers as the Ṣāḥib al-Fayḍa, the Bringer of the Evental Flood of Gnosis. A prolific author and teacher, he emerged from an intellectual formation shaped entirely by the West African scholarly tradition. He studied exclusively in the region, primarily under the guidance of his father, al-Ḥājj ʿAbd Allāh Niasse (d. 1922), whose own formation placed him within a lineage of West African scholars who had, from the fifteenth century onward, contributed substantially to Islamic theology, logic, jurisprudence, and spirituality. Figures such as Aḥmad ibn Aqīt al-Timbukti, al-Kashnawī al-Fulānī, ʿUthmān dan Fodio, and Aḥmadu Bamba left an enduring legacy of rational sciences and theological works that shaped the scholarly environment of the region.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">A compelling anecdote underscores his erudition: he is reported to have memorised Fakhr al-Dīn al-Rāzī’s Mafātīḥ al-Ghayb in its entirety, one of the most philosophically sophisticated Qurʾānic commentaries in the classical tradition. This command of the tradition positions him as a significant interlocutor within the broader landscape of Islamic thought. The compiler of the Arabic edition, Muḥammad ibn Shaykh ʿAbd Allāh, characterises the Shaykh’s relationship to the Prophet, peace and blessings be upon him, as “the vertebral column of the fruits of his ceaseless interaction with the world and his constant articulation of his biography,” a relationship, he adds, “that no word can express and no speech can convey.” In his gathered collections of Muḥammadan praise poetry there are approximately six thousand verses, and in every verse, as the compiler writes, “you read and hear depth and abundance, and you feel the breadth of the praiser and the greatness of the praised.”</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">The scope of Niasse’s scholarly mission extended across the world, encompassing countries across Africa and destinations as diverse as Paris, Cairo, Beirut, Tehran, India, Hong Kong, and China. Among the fruits of this effort, the compiler writes, was that “there entered into Islam at his hands, from the various peoples of the inhabited world, what the means of counting and enumeration failed to enumerate.” His daʼwa was accompanied by a sustained intellectual engagement with the challenges of his age, his opposition to colonialism and its cultural consequences finding expression in his “African for the Africans” essay and other works. Tafsīr was a fitting medium for Niasse’s intellectual contributions. His scholarly audience, referred to as al-muntahūn (the accomplished), was deeply trained in the Islamic sciences. These were sessions in which scholars initiated the gathering and laypeople joined, demonstrating the accessibility and dynamism of his teachings.</p>
        <h2 className="font-english text-gold text-xl font-semibold mt-10 mb-4 pb-3 border-b border-gold/20">Fī Riyāḍ al-Tafsīr: Origins, Character, and Scope</h2>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">Fī Riyāḍ al-Tafsīr li-l-Qurʾān al-Karīm is a ten-volume monumental work composed for Niasse’s community and a wider readership. The work originated as an oral commentary delivered in the setting of his teaching circle. The tafsīr that has reached us was delivered in Arabic in 1383 AH (c. 1963–64). It was recorded on cassette tapes and subsequently transcribed by the compiler, Muḥammad ibn Shaykh ʿAbd Allāh al-Tijānī al-Ibrāhīmī, who subjected the text to a rigorous process of hadith verification and scholarly annotation.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">The compiler acknowledges the challenges of transcribing oral speech: the density of pronominal reference, the rapid movement of inflection, and the inevitable gap between spoken expression and written text. He undertook the work, as he writes, out of concern that the recordings, scattered among the khalīfas and companions of the Shaykh, might be lost. The hadith apparatus alone records more than six thousand citations, traced wherever possible to their canonical sources across the ṣaḥīḥayn, the Sunan collections, and the wider hadith literature.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">The work was authorised for publication by the Niasse family, with unrestricted permission granted for its writing, verification, printing, and dissemination. The scholarly foundation of the Arabic text is the compiler’s labour of more than a decade, to which this edition is deeply indebted. The commentary engages the full range of Islamic scholarly disciplines, moving from grammatical analysis of Qurʾānic syntax to discussions of divine attributes, and from legal rulings to the direct address of the spiritual community. Niasse draws on the great works of the tafsīr tradition, especially the Rūḥ al-bayān of Ismāʿīl Ḥaqqī al-Burūsawī, the Ḥāshiya of al-Ṣāwī, alongside Tafsīr al-Jalālayn, while consistently returning to the oral, pedagogical, and spiritually formative dimensions of Qurʾānic engagement. West Africa has its own tafsīr tradition of considerable antiquity. The oldest known locally composed Arabic tafsīr dates to the first half of the eighteenth century, and the tradition deepened substantially through the nineteenth and twentieth centuries. Fī Riyāḍ al-Tafsīr stands as the most comprehensive and intellectually ambitious work in this tradition.</p>
        <h2 className="font-english text-gold text-xl font-semibold mt-10 mb-4 pb-3 border-b border-gold/20">This Edition: Structure, Method, and Translation Approach</h2>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">The present edition presents the Arabic text of Fī Riyāḍ al-Tafsīr in the Warsh ʿan Nāfiʼ rasm, the orthographic standard of North and West Africa in which the tafsīr was delivered, with an English translation on facing pages. The edition is structured in seven volumes, each corresponding to one of the seven manzils, the weekly Qurʾānic recitation cycle that Niasse himself practised and celebrated in verse. He enumerated the opening sūra of each manzil in verse and invoked two of the Qurʾān’s names, al-Furqān (the Criterion) and al-Jamʼ (the Joining):</p>
        <blockquote className="my-4 ml-6 pl-4 border-l-2 border-gold/40 font-english text-sm text-white/75 italic leading-8">Al-Fātiḥah, al-Māʾida, Yūnus, al-Isrāʾ,<br />al-Shuʿarāʾ, al-Ṣāffāt, Qāf, thus it is clarified.<br />He who joins the Criterion with the Joining<br />completes a full recitation of the Criterion.</blockquote>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">This structure reflects fidelity to the Shaykh’s own relationship to the Qurʾān. Qurʾānic audio is presented per verse using the recitation of Maḥmūd Khalīl al-Ḥuṣarī (1917–1980) in the Warsh riwāya. The translation proceeds from a commitment to scholarly precision and readability. The register is formal academic prose that preserves the oral cadences of the original, its directness, its rhythmic repetitions, and its transitions between legal analysis and spiritual address. Technical terms are retained in Arabic on first occurrence, with English equivalents in parentheses, and thereafter used in transliteration. The transliteration follows IJMES conventions throughout.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">Three translation choices warrant explicit statement. First, the Basmala is rendered “By Allāh’s Name, The Entirely Merciful, The Especially Merciful,” preserving the theological distinction between al-Raḥmān and al-Raḥīm that Niasse himself elaborates at length. Second, the term ʿabd is translated as “slave” throughout, as the more precise rendering of the term’s theological weight, the relationship of complete ontological submission that ʿabd carries in Niasse’s usage. Third, the phrase al-ḥamdu lillāh is rendered as two words, “al-ḥamdu lillāh (The Praise is for God),” preserving both the Arabic formula and its syntactic structure.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">The footnote apparatus throughout this edition preserves all of Niasse’s original scholarly citations, to the hadith collections, to al-Suyūṭī’s al-Itqān, to al-Ghazālī, to Ibn ʿArabī, traced to their canonical sources. Translator’s notes are added only where necessary and are distinguished from the Arabic compiler’s footnotes.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">The digital edition of this work is accessible at niassetafsir.com, where the bilingual text and audio resources are made available as a free scholarly resource.</p>
        <h2 className="font-english text-gold text-xl font-semibold mt-10 mb-4 pb-3 border-b border-gold/20">A Note on Transliteration and Conventions</h2>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">Arabic transliteration follows IJMES conventions throughout. The following honorifics are retained in abbreviated form: r.a. (raḍiya Allāhu ʿanhu/ʿanhā, “may Allāh be pleased with him/her”), used following the names of Companions and recognized saints; ṣ.a.w.s. (ṣallā Allāhu ʿalayhi wa-sallam, “may Allāh’s peace and blessings be upon him”), used following the name of the Prophet. Qurʾānic citations are given in the form Q. followed by chapter and verse numbers. Technical Arabic terms are given in transliteration on first occurrence with an English equivalent in parentheses; thereafter they appear in transliteration only. The Qurʾānic text in this edition follows the Warsh ʿan Nāfiʼ rasm.</p>
        {/* Acknowledgements section withheld pending final publication */}
  <h2 className="font-english text-gold text-xl font-semibold mt-10 mb-4 pb-3 border-b border-gold/20">Dedication</h2>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">To Ṣāḥib al-Fayḍa and his secret that is not sterile.</p>
        <p className="font-arabic text-gold text-center text-lg leading-9 my-2" dir="rtl">وَأَشْكُرُ رَبّي أَنَّ سِرّي لَيْسَ عَاقِرًا</p>
        <p className="font-arabic text-gold text-center text-lg leading-9 my-2" dir="rtl">فَحَتّى الأَدْنى مِنْ بَنيَّ يَفْنى</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">“And I thank my Lord that my secret is not sterile or barren,</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">for even the least adequate of my followers will achieve annihilation.”</p>
        <p className="font-arabic text-gold text-center text-lg leading-9 my-2" dir="rtl">تَسَمَّى رِجَالٌ بِالخَدِيمِ وَإِنَّنِي    أُسَاجِلُهُمْ لَا أَنْثَنِي وَأُسَابِقُ</p>
        <p className="font-arabic text-gold text-center text-lg leading-9 my-2" dir="rtl">أُسَابِقُهُمْ مَا عِشْتُ فِيكَ وَإِنْ أَمُتْ    يُسَاجِلُهُمْ فَرْعِي وَفِيكَ يُسَابِقُ</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">“Men have called themselves ‘The Servant’ [of the Prophet], but I compete with them, never yielding, and I outstrip them.</p>
        <p className="font-english text-white leading-relaxed mb-3 text-justify">I outstrip them as long as I live in you, and if I die, my branch will compete with them, and in you, will outstrip them.”</p>
        <p className="font-english text-white/35 text-xs pl-4 border-l-2 border-gold/20 my-4">Ibrāhīm Niasse, “Nūr al-Ḥaqq” (The Light of Truth), verses under the letter bāʾ, in Al-Dawāwīn al-Sitt (Beirut: Dār al-Fikr, 2009). See also Muḥammad ibn al-Shaykh ʿAbdullāh, Āfāq al-Shiʿr ʿind al-Shaykh Ibrāhīm Niyās (2018).</p>
      <div className="mt-12 pt-6 border-t border-gold/15 text-center">
        <Link href="/lesson/1"
          className="font-english text-sm text-bg bg-gold hover:bg-gold-light px-5 py-2 rounded-lg font-semibold transition-all">
          Begin Reading → Lesson One
        </Link>
      </div>
    </main>
  );
}
